version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm test -- --coverage
      - store_test_results:
          path: ./__tests__/results
      - store_artifacts:
          path: ./__tests__/results/test-results.xml
          prefix: tests
      - store_artifacts:
          path: ./coverage
          prefix: coverage
      